package br.tiagohm.nestalgia.core

enum class ExpansionPortDevice {
    NONE,
    ZAPPER,
    FOUR_PLAYER_ADAPTER,
    ARKANOID,
    OEKA_KIDS_TABLET,
    FAMILY_TRAINER_MAT,
    KONAMI_HYPER_SHOT,
    FAMILY_BASIC_KEYBOARD,
    PARTY_TAP,
    PACHINKO,
    EXCITING_BOXING,
    JISSEN_MAHJONG,
    SUBOR_KEYBOARD,
    BARCODE_BATTLER,
    HORI_TRACK,
    BANDAI_HYPER_SHOT,
    ASCII_TURBO_FILE,
    BATTLE_BOX,
}